name: CI
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq nasm
      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy-3.7'
          architecture: x64
      - name: install dependencies
        run: |
          pip install mypy
      - name: run tests
        run: |
          mypy ./porth.py
          python ./test.py
          python ./test.py -f ./examples/
